### ISSUE TITLE
Inquietud

### ISSUE THREAD

**Issue by ghost** [atSistemas/cygnus#1]
Hola, he estado siguiendo información de este repositorio, veo que se encuentra asociado a un post, mas sin embargo tengo la duda sobre la configuración que están implementando, ya se encuentra 100% terminada en desarrollo?, porque no veo la función principal de zuul de hacer el proxy hacia las url de los servicios, o no se si aun me falta cosas por revisar.

Cordialmente,

Jaider.

**Comment by nullp0int3r** [comment]
Hola @jaider2523 , el proyecto está en desarrollo. La función de Zuul es hacer de api-gataway entre los servicios. Obtiene los endpoints de las distintas instancias a balancear de Eureka. No sé si resuelvo tu inquietud ;)
Un saludo.

**Comment by ghost** [comment]
@nullp0int3r  Gracias por tu respuesta, mi principal duda era saber el estado del desarrollo, porque en la configuracion de ZUUL no veía el enrutamiento hacia los endpoints, entonces me surgió la inquietud sino estaba terminado o que existía una implementación distinta que no conociera y pudiera ser de ayuda.

De todas maneras muchas gracias y seguiré atento al desarrollo del proyecto.

**Comment by nullp0int3r** [comment]
@jaider2523 , Zuul obtiene su configuración del servidor central (spring cloud config) en tiempo de bootstrap. A su vez, este config-server obtiene la configuración del repo: https://github.com/atSistemas/cygnus-config
Ahí encontrarás el enrutamiento que te faltaba ;)
Un saludo.

**Comment by Jonathangt** [comment]
Hola, estoy siguiendo tu guia de arquitectura de microservicos pero al querer levantar el servivio sadr me bota un error 
`
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.2.RELEASE)

2019-01-29 21:14:41.154  INFO 1672 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from
 server at: http://config-server:8888
2019-01-29 21:14:44.623  INFO 1672 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from
 server at: http://config-server:8888
2019-01-29 21:14:45.748  INFO 1672 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from
 server at: http://config-server:8888
2019-01-29 21:14:46.967  INFO 1672 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from
 server at: http://config-server:8888
2019-01-29 21:14:48.320  INFO 1672 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from
 server at: http://config-server:8888
2019-01-29 21:14:49.799  INFO 1672 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from
 server at: http://config-server:8888
2019-01-29 21:14:49.814  WARN 1672 --- [           main] o.s.boot.SpringApplication               : Error handling faile
d (ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springfr
amework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@342d8fa7: startup date [Wed Dec 31 19:00:00
COT 1969]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@14e7f6c7)
2019-01-29 21:14:49.830 ERROR 1672 --- [           main] o.s.boot.SpringApplication               : Application startup
failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySource
Locator.java:130) ~[spring-cloud-config-client-1.2.2.RELEASE.jar:1.2.2.RELEASE]
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.i
nvoke(<generated>) ~[spring-cloud-config-client-1.2.2.RELEASE.jar:1.2.2.RELEASE]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.4.RELEASE.jar:4.3.
4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
 ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[s
pring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.jav
a:74) ~[spring-retry-1.1.4.RELEASE.jar:na]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276) ~[spring-retry-1.1.4.RELEAS
E.jar:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157) ~[spring-retry-1.1.4.RELEASE.
jar:na]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:101)
~[spring-retry-1.1.4.RELEASE.jar:na]
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOpe
rationsInterceptor.java:119) ~[spring-retry-1.1.4.RELEASE.jar:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[s
pring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~
[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$f78aef4e.l
ocate(<generated>) ~[spring-cloud-config-client-1.2.2.RELEASE.jar:1.2.2.RELEASE]
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBoot
strapConfiguration.java:89) ~[spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635) [spring-boot-1.4.2.R
ELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:349) [spring-boot-1.4.2.RELE
ASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.2.RELEASE.jar:1.4
.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.
4.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.
4.2.RELEASE]
        at com.atsistemas.cygnus.services.sadr.Application.main(Application.java:13) [classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:558) [spring-boot-maven-
plugin-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config-server:88
88/sadr/default": config-server; nested exception is java.net.UnknownHostException: config-server
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:633) ~[spring-web-4.3.4.RELEASE.jar:4
.3.4.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580) ~[spring-web-4.3.4.RELEASE.jar:4.3
.4.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498) ~[spring-web-4.3.4.RELEASE.jar:4.
3.4.RELEASE]
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigService
PropertySourceLocator.java:170) ~[spring-cloud-config-client-1.2.2.RELEASE.jar:1.2.2.RELEASE]
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySource
Locator.java:91) ~[spring-cloud-config-client-1.2.2.RELEASE.jar:1.2.2.RELEASE]
        ... 25 common frames omitted
Caused by: java.net.UnknownHostException: config-server
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_192]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_192]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_192]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_192]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_192]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_192]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_192]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_192]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_192]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_192]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_192]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_192]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_192]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_192]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_192]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpReq
uest.java:78) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHtt
pRequest.java:48) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring
-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:619) ~[spring-web-4.3.4.RELEASE.jar:4
.3.4.RELEASE]
        ... 29 common frames omitted

[WARNING]
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run (AbstractRunMojo.java:558)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate (ConfigServicePropertySourceLoc
ator.java:130)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invok
e (<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke (MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint (CglibAopProxy.java:720)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (ReflectiveMethodInvocation.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry (RetryOperationsInterceptor.java:7
4)
    at org.springframework.retry.support.RetryTemplate.doExecute (RetryTemplate.java:276)
    at org.springframework.retry.support.RetryTemplate.execute (RetryTemplate.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke (RetryOperationsInterceptor.java:101)
    at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke (AnnotationAwareRetryOperat
ionsInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept (CglibAopProxy.java:655)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$f78aef4e.locat
e (<generated>)
    at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize (PropertySourceBootstr
apConfiguration.java:89)
    at org.springframework.boot.SpringApplication.applyInitializers (SpringApplication.java:635)
    at org.springframework.boot.SpringApplication.prepareContext (SpringApplication.java:349)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:313)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1186)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1175)
    at com.atsistemas.cygnus.services.sadr.Application.main (Application.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run (AbstractRunMojo.java:558)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config-server:88
88/sadr/default": config-server; nested exception is java.net.UnknownHostException: config-server
    at org.springframework.web.client.RestTemplate.doExecute (RestTemplate.java:633)
    at org.springframework.web.client.RestTemplate.execute (RestTemplate.java:580)
    at org.springframework.web.client.RestTemplate.exchange (RestTemplate.java:498)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment (ConfigServicePro
pertySourceLocator.java:170)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate (ConfigServicePropertySourceLoc
ator.java:91)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invok
e (<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke (MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint (CglibAopProxy.java:720)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (ReflectiveMethodInvocation.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry (RetryOperationsInterceptor.java:7
4)
    at org.springframework.retry.support.RetryTemplate.doExecute (RetryTemplate.java:276)
    at org.springframework.retry.support.RetryTemplate.execute (RetryTemplate.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke (RetryOperationsInterceptor.java:101)
    at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke (AnnotationAwareRetryOperat
ionsInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept (CglibAopProxy.java:655)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$f78aef4e.locat
e (<generated>)
    at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize (PropertySourceBootstr
apConfiguration.java:89)
    at org.springframework.boot.SpringApplication.applyInitializers (SpringApplication.java:635)
    at org.springframework.boot.SpringApplication.prepareContext (SpringApplication.java:349)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:313)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1186)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1175)
    at com.atsistemas.cygnus.services.sadr.Application.main (Application.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run (AbstractRunMojo.java:558)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.net.UnknownHostException: config-server
    at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:184)
    at java.net.PlainSocketImpl.connect (PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect (SocksSocketImpl.java:392)
    at java.net.Socket.connect (Socket.java:589)
    at java.net.Socket.connect (Socket.java:538)
    at sun.net.NetworkClient.doConnect (NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer (HttpClient.java:463)
    at sun.net.www.http.HttpClient.openServer (HttpClient.java:558)
    at sun.net.www.http.HttpClient.<init> (HttpClient.java:242)
    at sun.net.www.http.HttpClient.New (HttpClient.java:339)
    at sun.net.www.http.HttpClient.New (HttpClient.java:357)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient (HttpURLConnection.java:1220)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0 (HttpURLConnection.java:1156)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect (HttpURLConnection.java:1050)
    at sun.net.www.protocol.http.HttpURLConnection.connect (HttpURLConnection.java:984)
    at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal (SimpleBufferingClientHttpReques
t.java:78)
    at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal (AbstractBufferingClientHttpRe
quest.java:48)
    at org.springframework.http.client.AbstractClientHttpRequest.execute (AbstractClientHttpRequest.java:53)
    at org.springframework.web.client.RestTemplate.doExecute (RestTemplate.java:619)
    at org.springframework.web.client.RestTemplate.execute (RestTemplate.java:580)
    at org.springframework.web.client.RestTemplate.exchange (RestTemplate.java:498)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment (ConfigServicePro
pertySourceLocator.java:170)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate (ConfigServicePropertySourceLoc
ator.java:91)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invok
e (<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke (MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint (CglibAopProxy.java:720)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (ReflectiveMethodInvocation.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry (RetryOperationsInterceptor.java:7
4)
    at org.springframework.retry.support.RetryTemplate.doExecute (RetryTemplate.java:276)
    at org.springframework.retry.support.RetryTemplate.execute (RetryTemplate.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke (RetryOperationsInterceptor.java:101)
    at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke (AnnotationAwareRetryOperat
ionsInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept (CglibAopProxy.java:655)
    at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$f78aef4e.locat
e (<generated>)
    at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize (PropertySourceBootstr
apConfiguration.java:89)
    at org.springframework.boot.SpringApplication.applyInitializers (SpringApplication.java:635)
    at org.springframework.boot.SpringApplication.prepareContext (SpringApplication.java:349)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:313)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1186)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1175)
    at com.atsistemas.cygnus.services.sadr.Application.main (Application.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run (AbstractRunMojo.java:558)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.568 s
[INFO] Finished at: 2019-01-29T21:14:50-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:run (default-cli) on proj
ect sadr: An exception occurred while running. null: InvocationTargetException: Could not locate PropertySource and the
fail fast property is set, failing: I/O error on GET request for "http://config-server:8888/sadr/default": config-server
; nested exception is java.net.UnknownHostException: config-server: Unknown host config-server -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by nullp0int3r** [comment]
Hola Jonathan,
Parece que el servicio no encuentra el Config server : UnknownHostException:
config-server: Unknown host config-server
De todas formas, para desarrollo en local y no depender de un Config server
puedes poner la property "failfast=false" y arrancar con la configuración
local del application.yml

Saludos!

**Comment by Jonathangt** [comment]
Hola
________________________________
De: nullp0int3r <notifications@github.com>
Enviado: miércoles, 30 de enero de 2019 3:26
Para: atSistemas/cygnus
Cc: Jonathan; Comment
Asunto: Re: [atSistemas/cygnus] Inquietud (#1)

Hola Jonathan,
Parece que el servicio no encuentra el Config server : UnknownHostException:
config-server: Unknown host config-server
De todas formas, para desarrollo en local y no depender de un Config server
puedes poner la property "failfast=false" y arrancar con la configuración
local del application.yml

Saludos!
